Develop sinatra memo app
yokomaru/sinatra-memo-app pull request #1
Opened 2024-06-05 09:47 UTC by yokomaru

2024-06-09 14:07 UTC, u1tnk requested changes

2024-06-09 14:07 UTC, u1tnk commented on app.rb
> +  hash = { 'id': max_id.to_s, 'title': h(params[:title]), 'content': h(params[:content]) }
escapeしたものを保存するのはデータが壊れるのでNGです。
escapeは表示するとにしましょう。

また、  hashという変数名もNGですね。変数名は何が入っているか推測する大事な情報なので中身を類推できる名前にしましょう。

2024-06-09 14:07 UTC, u1tnk commented on app.rb
> +  Memo.save(@memos)
この saveは 入力がおかしいときは失敗して falseになるのでその場合の処理をしましょう。
絶対に失敗しない場合もありますが、その時はバグが起きたときに検知するために `save!`にします。なので `save`の戻り値をチェックしないことは基本的にありません。

2024-06-09 14:07 UTC, u1tnk commented on models/memo.rb
> +  FILE_PATH = 'public/memo.json'
この memo.json は
- パスが public以下なのは良くないです。publicに直接公開するための場所です。cssとかは適しています。
- memo.jsonをgitにcommitしているのはNGです。 頻繁に編集するデータファイルはcommitせずに ignoreするようにしましょう。

2024-06-09 14:07 UTC, u1tnk commented on models/memo.rb
> +    rescue StandardError
StandardErrorで rescueすると全然関係無いエラーでも通ってしまうので良くないですね。ファイルが無いときを想定してると思うのでそのときに発生するエラーにしましょう。
ちなみにファイルが無いときのケアができてるのでなおさら、 memo.jsonを作ってコミットしておく必要は無さそうです。

2024-06-09 14:07 UTC, u1tnk commented on models/memo.rb
> +  def self.find_by_id(memos, id)
これは 保存されているmemosの中から 一件欲しいんですよね？でしたら この中で allを呼ん であげればもっとシンプルに使えると思います。

2024-06-09 14:07 UTC, u1tnk commented on models/memo.rb
> +  def self.destroy(memos, id)
この destroyもこのメソッドで一緒にsaveしてやれば使う側が「destroyを使った後はsaveしないと保存されない」という事を理解する必要は無くなると思います。

2024-06-11 02:35 UTC, yokomaru commented on app.rb
> +  hash = { 'id': max_id.to_s, 'title': h(params[:title]), 'content': h(params[:content]) }
ありがとうございます！
XSS対策はブラウザ上で攻撃者が書いたスクリプトが実行されることを防ぐために行うものだとあらためて理解しました。データ自体は改変せず、view側で都度エスケープするようにいたします。

変数名も失礼いたしました！シンプルにmemoと修正しました。

2024-06-11 02:38 UTC, yokomaru commented on app.rb
> +  Memo.save(@memos)
save処理を行うpost、patch、deleteにて以下のイメージで戻り値をチェックする処理を追加しました。

```ruby
  if Memo.save(params)
    redirect '/'
  else
    erb xxx
  end
```

2024-06-11 02:40 UTC, yokomaru commented on models/memo.rb
> +  FILE_PATH = 'public/memo.json'
以下承知いたしました！

- publicに直接公開するための場所
- 頻繁に編集するデータファイルはcommitせずに ignoreする

上記を踏まえて対応行いました。

- memo.jsonのパスをdb/memo.jsonに変更
- .gitignoreにdb/memo.jsonを追加
- dbフォルダに.gitkeepを追加

2024-06-11 02:42 UTC, yokomaru commented on models/memo.rb
> +    rescue StandardError
> StandardErrorで rescueすると全然関係無いエラーでも通ってしまうので良くないですね。ファイルが無いときを想定してると思うのでそのときに発生するエラーにしましょう。

エラーをもみ消さないように気をつけます！
今回ファイルがないとき・ファイルの中身がないときの処理を再度考え直し、rescueはやめて以下の対応に変更しました。

- ファイルがないとき
   - Memo.create_dbを追加
   - ruby app.rbを実行した際にファイルがなければmemo.json(中身は空の配列)を作成
- ファイルの中身がないとき
   - File.readして中身があればその内容を、なければ空の配列を返す

2024-06-11 02:47 UTC, yokomaru commented on models/memo.rb
> +  def self.destroy(memos, id)
https://github.com/yokomaru/sinatra-memo-app/pull/1#discussion_r1632308715

こちらのメッセージと合わせて、app.rbでallやsaveなどを呼んでデータ更新を行なっていた箇所を
Memoモデルにparamを渡して処理するように変更いたしました。

https://github.com/yokomaru/sinatra-memo-app/pull/1/commits/2f2af2438d7646dd85e4665a60ec4c83e88dbe3a
https://github.com/yokomaru/sinatra-memo-app/pull/1/commits/8a1ba71909b6f053685f9d3fb7ebc9e2d1872bb4

2024-06-11 15:26 UTC, u1tnk approved these changes
細かいところだけなんでOKです 🙆‍♀️ 
app.rbめっちゃスッキリしましたね 👍

2024-06-11 15:26 UTC, u1tnk commented on models/memo.rb
> +    memo = { 'id': max_id.to_s, 'title': params[:title], 'content': params[:content] }
細かいので修正しなくても良いですが、以下のように変数に入れなくても見やすいですし、 `<<` を使う方がrubyではよく見ます。

```
memos << { 'id': max_id.to_s, 'title': params[:title], 'content': params[:content] }
```

2024-06-12 09:22 UTC, yokomaru commented on models/memo.rb
> +    memo = { 'id': max_id.to_s, 'title': params[:title], 'content': params[:content] }
コメントありがとうございます！！
コードがより短くなりすっきりしました！今後配列に追加する処理は積極的に`<<`を使います！

2024-06-12 09:23 UTC, yokomaru commented
OKいただいたのでマージいたします！

2024-06-12 09:24 UTC, merged